[project]
name = "langid"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.5.0",
    "mediapipe>=0.10.32",
    "mistral-common>=1.9.0",
    "ruff>=0.15.13",
    "sentencepiece>=0.2.1",
    "tiktoken>=0.12.0",
    "transformers>=5.0.0",
]
